React package
neoxia/apoyo pull request #18
Opened 2021-05-22 08:51 UTC by Jujulego

Utilities for React

2021-05-26 07:16 UTC, sascha245 commented
Hello @julien-capellari,

I approved the run of the CI worklow. On your next commits, the CI should now launch correctly.

I am currently working on automating the publishing of new packages / new versions via the CI when a PR is merged. This will ease the development and deployment of this new package.

Don't forget to use a 0.x.x version for your package until your API has become more stable.

2021-05-26 07:48 UTC, sascha245 commented on packages/react/src/useInterval.ts
> +export default useInterval
It would be better to use `export const useInterval = ...` instead of an default export here.

2021-05-29 15:43 UTC, sascha245 commented
Hello, je vais te faire une review un peu plus complète que la dernière fois sous peu.

Cependant, ici déjà une première question: Pourquoi ne pas utiliser "react-use" (https://github.com/streamich/react-use), pour ce genre d'utils? Cette librairie est aussi 100% three-shakable et contient aussi pas mal de hooks divers, donc les 2 que tu souhaites mettrent en place ici.

2021-05-29 16:03 UTC, sascha245 requested changes

2021-05-29 16:03 UTC, sascha245 commented on packages/react/package.json
> +  "dependencies": {
Maybe make react / react-dom peerDependencies?
This way, the user has more control on which react version he wishes to install.

2021-05-29 16:40 UTC, Jujulego commented
> Hello, je vais te faire une review un peu plus complète que la dernière fois sous peu.
> 
> Cependant, ici déjà une première question: Pourquoi ne pas utiliser "react-use" (https://github.com/streamich/react-use), pour > ce genre d'utils? Cette librairie est aussi 100% three-shakable et contient aussi pas mal de hooks divers, donc les 2 que tu souhaites mettrent en place ici.
> 
> Il faudrait donc voir quelle serait la "plus value" de @apoyo/react.
>

C'est que pour ces 2 là c'est pas très intéressant, et si j'était de mauvaise foix, pk utiliser @apoyo/std au lieu de lodash, @apoyo/decoders au lieu de class-validator, joi ou [yup](https://www.npmjs.com/package/yup) (si tu connaissais pas c'est joi mais avec les types).
Déjà c'est la première librairie react que je mets en place (et rien que ça pour moi c'est déjà intéressant) du coup je me suis servi de ces 2 hooks que j'avais déjà codés et testé dans un ancien projet pour mettre la lib en place, mais je réfléchis a des trucs plus "apoyo" spécifiques, comme un `useApoyoPipe` ou encore un moyen d'utiliser les decoders sur les formulaires en react (intégrés avec [react-hook-form](https://react-hook-form.com/) par example)

2021-05-29 16:42 UTC, Jujulego commented on .gitattributes
> +* text=auto eol=lf
Mmh j'en avais besoin pour cloner le projet sur windows (a cause de ce foutu prettier et sa règle [endOfLine](https://prettier.io/docs/en/options.html#end-of-line))

2021-05-29 16:45 UTC, Jujulego commented on tsconfig.common.json
> +    "skipLibCheck": true,
la pipeline plante dans jest sinon : https://app.netlify.com/sites/nx-apoyo/deploys/60b25baf89e4a60007abbf01

2021-05-29 16:50 UTC, sascha245 commented on .gitattributes
> +* text=auto eol=lf
Mmh, je suis aussi sur windows, mais je n'ai encore pas trop eu de soucis à cause de cela.
 
Après un premier "format document" d'un nouveau fichier, le fichier passe automatiquement en LF. Et sinon eslint / prettier se pleint, ce qui est voulu. Nous souhaitons éviter d'avoir un mix de CRLF et LF dans le projet.

Je vais tester une fois si ce .gitattributes impacte le reste des fichiers. Si ce n'est pas le cas, nous pouvons ajouter ce fichier mais de préférence comme dit dans une PR séparée (j'ai pu voir qu'il y a une branche pour cela si je me trompe pas).

2021-05-29 17:11 UTC, Jujulego commented on .gitattributes
> +* text=auto eol=lf
Le .gitattributes force git a cloner les fichier avec lf et pas crlf comme il le fait normalement sur Windows c'est la seule chose que ça change ... Mais comme ça quand on clone le projet tout les fichier sont bon et eslint ne met pas une erreur à toutes les lignes

2021-05-29 17:15 UTC, sascha245 commented
Hello,

Je ne veux pas dire que je suis contre de créer un package @apoyo/react, mais j'aimerais bien avoir un peu plus de visibilité sur le type de features ce que tu souhaite ajouter et qui pourrait constituer de vrai gain par rapport à d'autres packages / solutions.

Exemple:
- des hooks pour créer des formes reactives?
- utils pour améliorer tout ce qui est injection de dépendences?
- etc... 

A toi de voir quelles sont les choses dont tu as le plus souvent besoin sur un projet React.
Le but ici n'est pas de les implémenter d'un coup, mais de tout simplement avoir une liste de features intéressantes à implémenter pour une V1. 

Prenons par exemple le package std / decoders:

**std**: 
- plus léger que les packages mentionnées + three-shakable
- des features bien différentes sont inclusent (utils pour promise, tasks, results, ord, enum, etc...)

**decoders**:
- tres léger + three-shakable
- très facile à créer des validateurs complexes customs
- code source plutôt simple
- inférence de type complète (joi n'en a pas, et pour yup j'avais lu qu'il y a des issues parfois)
- comparer à class-validator : des opérations plus poussées peuvent être réalisé bien plus facilement (omit certaines props, pick, partial, merge, union, etc...)

Donc dans les 2 cas, mêmes si les packages ne supportent pas toutes les features des packages "concurrents" et déjà établi, ils contiennent tout de même déjà un bon tat de features qui les rendent uniques.

Je m'excuse en tout cas pour mon commentaire précédent, je m'étais mal exprimé.

2021-05-29 17:35 UTC, sascha245 commented on tsconfig.common.json
> +    "skipLibCheck": true,
Mmh, très étrange que l'erreur arrive lors de build et non lors des tests.
Je te laisse bouger cette ligne dans le tsconfig.json local (packages/react), jusqu'à ce qu'on trouve une autre solution.

2021-05-29 17:41 UTC, Jujulego commented
> Je m'excuse en tout cas pour mon commentaire précédent, je m'étais mal exprimé.

Ne t'inquiète pas je suis moi-même un peu "cru" des fois ;)

Pour ce qui est des features proprement dites pour l'instant j'ai surtout 2 idées en rapport avec le reste de la lib :
- `useApoyoPipe` qui serait un wrapper autour du `pipe` de @apoyo/std et dans mon esprit ça resssemblerait à ça :
  ```typescript
    const res = useApoyoPipe(
       array,
       sort(...),
       ...
    );
  ```
  ça nous permettrait d'enrober pipe avec `useMemo` et ainsi d'améliorer les perfs dans une app React

- Intégrer les `@apoyo/decoders` avec la librairie react-hook-form (qui est purement géniale a mon avis)
  l'idée serait de faire qqch de similaire à ce qui est fait pour yup et joi justement : https://react-hook-form.com/get-started#SchemaValidation

Après j'ai aussi déjà développé d'autres "librairies" dans mes projets perso qui peuvent être intéressantes (notamment une pour les tableaux dont je suis assez fier :)) mais elles sont fortement liées à @material-ui ... et je voudrais pas ajouter ce genre de dépendances à la lib ...

2021-05-29 17:46 UTC, sascha245 commented on .gitattributes
> +* text=auto eol=lf
Ok c'est bien à savoir, c'est bien à mettre en place dans ce cas.
Je n'avais peut-etre pas eu ce problème de mon coté car j'ai du configuré cela de facon global sur git à un moment donnée sur mon PC.

2021-05-29 17:53 UTC, sascha245 commented on .gitattributes
> +* text=auto eol=lf
closed by #25

2021-05-29 18:21 UTC, sascha245 commented
Mmh, en soit "pipe" peut déjà être utilisé avec les hooks:

```ts
const ordTodo = pipe(
  Ord.string,
  Ord.contramap((todo: Todo) => todo.name)
)

const filtered = useMemo(() => pipe(
  todos,
  Arr.filter(todo => !todo.done),
  Arr.sort(ordTodo)
))
```

Il est parcontre aussi possible de créer un "Monad"/ une "box" du genre suivant:

```ts
export const Ref = {
  of, // create state (useState)
  map, // map over a specific state (useMemo)
  watch // watch a specific state (useEffect),
  ...
}

// Usage

const count = Ref.of(0) // Ref<number>
const double = pipe(
  count, 
  Ref.map(nb => nb * 2)
) // ReadonlyRef<number>

count.value // get value
count.value = 1 // call setter
```

... D'ailleurs c'est dommage que rxjs n'est pas plus utilisé pour React, c'est vraiment les 2 technos qui vont parfaitement ensemble, car tu peux très facilement unsub et éviter des erreurs où le state est modifié alors que le component a déjà été détruit.

Sinon oui, il faudrait que la lib reste un peu près inopinié, pour ne pas trop limité la lib à certaines situations.

2021-05-29 22:52 UTC, Jujulego commented
> Mmh, en soit "pipe" peut déjà être utilisé avec les hooks

Pas si simple, pour reprendre ton exemple, ce serait plutôt :
```typescript
const filtered = useMemo(() => pipe(
  todos,
  Arr.filter(todo => !todo.done),
  Arr.sort(ordTodo)
), [todos]) // << faut mettre les dépendances on peut peut-être simplifier la syntaxe, réduire les répétitions ...
```

Et le cas des promises / tasks est plus compliqué : on ne peut pas faire de "await" dans la fonction du composant ...

> Il est parcontre aussi possible de créer un "Monad"/ une "box" du genre suivant

Je crois que j'ai a peu prêt compris ton idée et non je pense que ce n'est pas faisable, ni même à conseiller, il y a plusieurs limites assez contraignantes à l'usage des hooks : https://fr.reactjs.org/docs/hooks-rules.html
Il faut absolument les appeler dans une fonction composant et pas ailleurs, ni même dans une boucle ou un if.

Et enfin pour rxjs, au final quand on y réfléchit, la lib ne sert pas a grand chose dans le cas de React (a mon avis) vu que React est déjà très reactif, tout est pensé dans react pour réagir uniquement. Le seul pour lequel ça peut être intéressant c'est les calls api, mais c'est assez compliqué à mettre en place pour les events UI, or c'est sur ce point que rxjs est la plus intéressante ...

Bon, je suis pas un fan du "global state" donc ça n'aide pas a défendre rxjs ... J'ai fais du redux pendant un temps, jusqu'au moment ou je me suis rendu compte qu'il fallait penser à nettoyer le state quand on quitte certaines fenêtres (quand on logout par exemple), alors que en principe en react quand le composant est unmount, son state est détruit avec lui.
Je trouve redux très verbeux pour pas grand chose (un context suffit largement), et niveau perfs j'ai tjs eu un gros doute ... Tu as un state global A et tes 100 composants suivent TOUS les évolutions du state, donc quand 1 truc évolue TOUS les composants sont rerendus (ou du moins recalculent pour vérifier s'il ne sont pas impactés) même s'il n'ont rien a voir avec la donnée modifiée. Alors que si tu as de petits states, seuls les composants concernés par la données sont impactés, ça réduit grandement les calculs. Après ce n'est que mon avis, j'ai pas fais, ni vu de benchmark sur le sujet.

Par contre j'ai peut-être un truc en réserve qui peut être intéressant : https://github.com/Jujulego/lucifer/tree/master/libs/react/api/src/lib
c'est une suite de hooks encapsulant axios pour faire des calls API. Ici axios serait difficile à changer car je me suis appuyé sur leurs CancelToken pour "arrêter" les requêtes en cours. J'ai ajouté un cache optionnel, qui permet de retourner immédiatement le résultat précédant pendant que le call api est en cours ce qui donne une interface plus rapide.
Mais le plus intéressant est ailleurs, à l'usage on peut "presque" retrouver les services de Angular, en version hooks :

```typescript
// On peut regrouper les différents calls apis
export const useUsersAPI = {
  all: () => useAPI.get<IUser[]>('/api/users'),

  get: (id: string) => useAPI.get<IUser>(`/api/users/${id}`),
  put: (id: string) => useAPI.put<IUpdateUser, IUser>(`/api/users/${id}`)
};

// On peut ensuite gérer une resource distante presque comme un state local
export const useUser(userId: string) {
  const { data: user, loading, reload, update } = useUsersAPI.get(id);
  const { send: put } = useUsersAPI.put(id);

  return {  
    user, loading,
    reload,
    put: useCallback(async (data: IUpdateUser) => {
      const result = await put(data);
      update(result); // update the get cache
      return result;
    }, [put, update]),
  }
};

// Ce qui donne au final un truc comme ça
export const User: FC<{ userId: string }> = ({ userId }) => {
  const { user, loading, update } = useUser(userId);

  if (loading) {
    return <p>Loading ...</p>
  }

  return (
    <>
      <p>{ user?.name }</p>
      <button onClick={() => update({ name: 'toto' })>Set name to toto</button>
    </>
  );
};
```

Pfiou ! j'ai rarement écrit autant !
 Et j'ai un autre truc du même niveau que les api mais pour les tableaux : https://github.com/Jujulego/lucifer/tree/master/libs/react/table/src/lib
Elle permet de mettre en place un tableau ... comme on écrirait un tableau en html, et ce tout en gérant le tri, les filtres, et la sélection. Il y a juste 2 points noirs: j'utilise des composants de material-ui et les données DOIVENT avoir un champs id ...
Ca demande un peu de travail pour lui supprimer ces dépendances mais c'est très sympa a l'usage : https://github.com/Jujulego/lucifer/blob/058b9a9cce0039865f6a59275c48e264c04b05e2/apps/lucifer-front/src/users/UserTable.tsx#L43-L77

2021-05-30 12:07 UTC, sascha245 commented
Hello,

Pour répondre à ton commentaire (celui un peu long):

- Pour l'histoire du "monad"/"box", si cela devrait être possible d'après mes connaissances des hooks reacts. Peut-etre pas aussi intensivement qu'avec des vraies systemes de reactivité, mais cela devrait déjà peut-etre couvrir un début:

Exemple très simple:
```ts
type Ref<T> = {
  value: T
}
type ReadonlyRef<T> = {
  readonly value: T
}

const Ref = {
  of: <T>(value: T): Ref<T> => {
    const [state, setState] = useState(value)
    return {
      get value() { return state },
      set value(val) {
         setState(val)
      }
    }
  },
  map: <A, B>(fn: (value: A) => B) => (ref: ReadonlyRef<A> | Ref<A>): ReadonlyRef<B> => {
    const newVal = useMemo(() => fn(ref.value), [ref.value])
    return {
      get value() { return newVal }
    }
  }
}

// Usage

const MyComponent = () => {
  const count = Ref.of(0)
  const double = pipe(count, Ref.map(n => n + 1))

  return <div>
    <p>Count: {count}, Double: {double}</p>
    <button onClick={ () => count.value = count.value + 1 }>
  </div>
}
```
Ce n'est qu'une implémentation naive, simplement pour illustrer le cas / pour montrer que cela marche (tant qu'il n'y a pas de condition/loop ou autre...)

Concernant Rxjs, je pense toujours que tu sous-estime encore un peu la "symbiose" entre React et Rxjs. En effet, Rxjs n'est pas que bon pour des calls API, mais pour un tas d'autres choses:

- Pour tout type d'opérations asynchrones:
  - timeout / interval
  - call api
  - debounce / throttle

Et le tout sans jamais avoir besoin de faire attention que le state est changé après la destruction de ton component.

- Tu peux réécrire des fonctions / utils / services utilisables au dehors de tes components React:

```ts
// Logic that is completely independent from React, can be used wherever you want
import { ajax } from 'rxjs/ajax';

const names$ = ajax
  .getJSON(api)
  .pipe(map(({ results: users }) => users.map(getName)));

// Subscribe to the endpoint in a component
const MyComponent = () => {
  const names = useObservable(names$, [])

  const els = names.map(name => <li>{name}</li>)
  return <ul>{els}</ul>
}
```

- Pour du state global (ex: stockage de ton token d'auth) dans tes services / hors components, cela revient déjà assez compliqué avec du React simple. Avec rxjs, cela revient à:

```ts
// Declare your reactive data
const token$ = new BehaviorSubject()

// Use your reactive data in a component
const MyComponent = () => {
  const token = useObservable(token$, undefined)

  return <p>Current Token: {token}</p>
}

// Update value outside of react after some time...
setTimeout(() => {
  token$.next("New token")
  // Your component should update
}, 5000)
```

Tu peux donc bien plus facilement créer du global state, partager ton global state entre tes différents services et souscrire au données dans tes components, que ce soit des données async ou non.

- Pour combler les soucis / les failles du système de "réactivité" de React (qui n'est en soit pas vraiment de la réactivité). Tu as ainsi accès à une tonne d'outils de rxjs qui peuvent te faciliter la vie.

Je te laisse peut-etre regarder une fois https://www.bitovi.com/blog/rxjs-with-react-pt-1 qui illustre certains de ces points.
Dit moi ce que t'en penses!

Je te souhaite en tout cas encore une bonne fin de weekend.

2021-06-05 08:32 UTC, closed without merging